Update palindrom-client to 5.0.0
Polyjuice/SysUpgrade pull request #28
Opened 2018-01-26 12:18 UTC by alshakero

2018-01-26 13:02 UTC, PatrykSzwer requested changes
You forgot to update bower-list.txt file! How dare you!

2018-01-26 13:39 UTC, PatrykSzwer requested changes
I assume that it should work with SC 2.3.x, but I'm getting errors about incompatibility (~no~ 2.4 compatiblity property in csproj)

EDIT: mb I meant that I'm getting incompatibility errors on SC 2.3.x, so there is probably compatibility attribute added with no reason.

2018-01-29 10:51 UTC, warpech commented
A project cannot be simultaneously compatible with 2.3 and 2.4. Let's keep this branch compatible with 2.4 only. 

The files from this branch must work with Starcounter 2.3.x when `<StarcounterVersionCompatibility>2.4</StarcounterVersionCompatibility>` is removed from `csproj`.

2018-01-31 09:19 UTC, PatrykSzwer approved these changes

2018-01-31 09:37 UTC, merged